### ISSUE TITLE
Restructure the code.

### ISSUE THREAD

**Issue by xsahil03x** [xsahil03x/Flutter_news_reader#4]

**Comment by grlwholifts** [comment]
hi, I would like to work on this. can I know how to proceed?

**Comment by madhukesh048** [comment]
hey @xsahil03x , anything i can work on?

**Comment by xsahil03x** [comment]
@ruchikabgosain , @madhukesh048 this was my second app in flutter. So the structure of the code is not as per standards. You can re-structure this code if you want and also segregate the business logic from UI logic.

**Comment by madhukesh048** [comment]
@xsahil03x sure!

**Comment by madhukesh048** [comment]
@xsahil03x I have migrated it to androidx [in this PR](https://github.com/xsahil03x/Flutter-News-Reader/pull/5)

**Comment by xsahil03x** [comment]
@madhukesh048 thanks for completing the step 1. :100:

**Comment by madhukesh048** [comment]
@xsahil03x I have restructured the code and fixed few minor bugs [in this PR](https://github.com/xsahil03x/Flutter-News-Reader/pull/6)
