### ISSUE TITLE
Implement Bloc pattern

### ISSUE THREAD

**Issue by xsahil03x** [xsahil03x/Flutter_news_reader#7]
Segregate the business logic and Api calls from the widget code.

**Comment by emersonsiega** [comment]
@xsahil03x I can handle this. I'll do it this weekend :)

**Comment by xsahil03x** [comment]
@emersonsiega yes, go on.

**Comment by xsahil03x** [comment]
Fixed in #9

**Comment by emersonsiega** [comment]
@xsahil03x So I've worked for some hours for nothing?
